### ISSUE TITLE
All three Kiwix appxbundles now fail to install with `0x80070490 : Element not found.`

### ISSUE THREAD

**Issue by Jaifroid** [microsoft/winget-pkgs#25765]
# Brief description of your issue

All three Kiiwx appxbundles - `winget install kiwix`, `winget install wikivoyage`, `winget install wikimed` - fail to install with an error like:
```
Install failed: error 0x80070490: Opening the package from location KiwixWebApp_1.6.0.0_AnyCPU.appxbundle failed.
0x80070490 : Element not found. 
```

# Steps to reproduce

Run `winget install kiwix`. It fails.

# Expected behavior

As these bundles were all previously validated, and as I can download each bundle and install it manually with the Windows UWP installer, I expect these to work. Installation via winget has worked perfectly on previous occasions.

# Actual behavior

They fail with the above error. It looks as if something has changed regarding winget's support of appxbundles. Please note that all these apps are WinRT HTML/JS apps. It may be relevant that recently these apps have started producing the `Validation-No-Executables` label during validation, and a tech has had to add a .validation file.

# Environment
```
Windows: Windows.Desktop v10.0.19043.1200
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

![image](https://user-images.githubusercontent.com/4304337/130571539-622dfc10-5c91-47df-b5fe-1cb0ac30d24e.png)

**Comment by OfficialEsco** [comment]
Steps to reproduce unclear, successfully installed all 3
![image](https://user-images.githubusercontent.com/15158490/130593359-fe6cea77-dc01-43ab-868b-5a7ad7b6a017.png)

Can you post the related logs from `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir`?

**Comment by Jaifroid** [comment]
Well I've just tried again, with same result.

![image](https://user-images.githubusercontent.com/4304337/130596024-d78aea48-7e46-49a2-873c-5cf693909c2b.png)

Will post log.

**Comment by Jaifroid** [comment]
Here's the log: [WinGet-2021-08-24-10-48-25.569.log](https://github.com/microsoft/winget-pkgs/files/7038274/WinGet-2021-08-24-10-48-25.569.log)

**Comment by OfficialEsco** [comment]
You could also try to change the Network setting for Winget, the default one is `Delivery Optimization` (which i used there) to `wininet` (browser protocol i believe)

```
 "Network": {
      "description": "Network settings",
      "type": "object",
      "properties": {
        "downloader": {
          "description": "Control which download code is used for packages",
          "type": "string",
          "enum": [
            "default",
            "wininet",
            "do"
          ],
          "default": "default"
        }
```

I think its like this?
```
 "Network": {
        "downloader": wininet
        }
```

Hopefully a technician will look into this, not like the logs explain more 🤦‍♂️
```
2021-08-24 10:48:32.116 [CORE] WinINet downloading from url: https://winget.azureedge.net/cache/manifests/k/Kiwix/KiwixJS/1.6.0.0/56ff-Kiwix.KiwixJS.yaml
2021-08-24 10:48:32.687 [CORE] Download hash: 8b159084e3ba1fdaadbce496846e68aad7c30de03e76eca7b5563b9eaa782d2c
2021-08-24 10:48:32.687 [CORE] Download completed.
2021-08-24 10:48:32.688 [CLI ] Manifest fields: Name [Kiwix JS], Version [1.6.0.0]
2021-08-24 10:48:32.692 [CLI ] Starting installer selection.
2021-08-24 10:48:32.692 [CLI ] Completed installer selection.
2021-08-24 10:48:34.291 [CLI ] Installer hash verified
2021-08-24 10:48:34.292 [CORE] Starting AddPackage operation #1: https://github.com/kiwix/kiwix-js-windows/releases/download/v1.6.0/KiwixWebApp_1.6.0.0_AnyCPU.appxbundleSkipSmartScreen: 1
2021-08-24 10:48:34.294 [CORE] Begin waiting for deployment #1
2021-08-24 10:48:34.294 [CORE] Begin blocking for deployment #1
2021-08-24 10:48:35.070 [CORE] Deployment failed #1: error 0x80070490: Opening the package from location KiwixWebApp_1.6.0.0_AnyCPU.appxbundle failed.
2021-08-24 10:48:35.071 [FAIL] E:\BA\97\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(50)\AppInstallerCLI.exe!00007FF6747F0499: (caller: 00007FF6747F0C19) Exception(1) tid(4cfc) 80070490 Element not found.

    Msg:[Install failed: error 0x80070490: Opening the package from location KiwixWebApp_1.6.0.0_AnyCPU.appxbundle failed.] 

2021-08-24 10:48:35.173 [CLI ] MSIX installer failed: 2147943568
2021-08-24 10:48:35.173 [CLI ] Terminating context: 0x80070490 at E:\BA\97\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:168 
```

This might be a MSIX issue on your side?

**Comment by Jaifroid** [comment]
Thanks @OfficialEsco. I don't think it's an MSIX issue because the packages install fine if I simply double-click them. There is no problem installing them with the standard (UWP) Windows installer, only with WinGet.

**Comment by OfficialEsco** [comment]
I did a quick search on one of the error codes last time and found a MSIX issue which is why i suggested that :)

Another thing you can do is, fork the repo, do `winget install -m <path to manifest>`, if still the same issue edit the InstallerType to Appx and try again, post the Log again to see if it throws a different error code

**Comment by Jaifroid** [comment]
Thank you very much for your helpful suggestions, @OfficialEsco. I have discovered that it works on my Windows 11 test installation. Therefore the issue is not with the packages themselves, but with the configuration of WinGet on my PC. It looks like a botched update of WinGet. I'll try removing and reinstalling first. I did validate the manifest installation when I made the PR for each package's manifest. I'll try again if uninstalling and reinstalling my version of WinGet doesn't do the trick. Will report back.

**Comment by Jaifroid** [comment]
Reinstalling AppInstaller from the GitHub repo doesn't cure the issue. Oddly, the version on the GitHub repo is older than the one I already have (from the Store), but I went ahead and installed it anyway. Same issue: winget install xxxxx results in `error 0x80070490`.

Manifest install (`winget install -m .\winget-pkgs\manifests\k\Kiwix\KiwixJS\1.6.0.0\`) now results in the same error. Strange.

**Comment by Jaifroid** [comment]
For reference, running `sfc /scannow` found some errors and supposedly fixed them. After reboot, however, the winget error still persists.

**Comment by Jaifroid** [comment]
Also for reference, installing a manifest for a desktop .exe programme works fine. The issue is with installing MSIX/appx/appxbundle. Once again, these install fine if I simply double-click the appxbundle downloaded from the same source. So the issue is definitely wiith winget. @denelon , would you have any clue what is going on or how I can fix my copy of winget? I've already tried to reinstall winget / downgrade to the GitHub version. It downgrades, but the issue isn't fixed.

**Comment by denelon** [comment]
@Jaifroid we will have to look into this. I don't see anything on the surface that would cause this behavior.

**Comment by jedieaston** [comment]
This is going to sound extremely dumb because every single Microsoft forum post says this, but have you tried `dism /Online /Cleanup-Image /RestoreHealth` from an elevated PowerShell/Command Prompt? I've had wacky issues with appx provisioning that have been fixed that way before.

**Comment by Jaifroid** [comment]
Thanks for the suggestion @jedieaston -- any suggestion at all is useful atm! I've just tried that: it says the operation completed successfully, but the issue persists, unfortunately. 😶

**Comment by jedieaston** [comment]
Can you try manually downloading one of the installers and running `Add-AppxPackage <path to installer>`? If it also fails we can get some more logs that way.

**Comment by Jaifroid** [comment]
Yes, that gives the following output (I also tried the suggested command):

![image](https://user-images.githubusercontent.com/4304337/130810926-3c10abc0-fa17-4ece-ad5a-1bbcbc4ec744.png)

**Comment by Jaifroid** [comment]
OK, `Add-AppxPackage` works fine on Windows PowerShell!

**Comment by Jaifroid** [comment]
... but winget also broken on Windows PowerShell...

![image](https://user-images.githubusercontent.com/4304337/130815852-467f19bd-2dec-41f8-8ee8-7a56c53c685a.png)

**Comment by jedieaston** [comment]
Totally spitballing, but did you try @OfficialEsco's suggestion of disabling Delivery Optimization and using the wininet downloader? It looks like that error is sometimes (at least, in a Insider Preview build of Windows 10 from two years ago...) linked to something with Delivery Optimization.

**Comment by Jaifroid** [comment]
@jedieaston Thanks for following up on that suggestion. So, I worked out I need to type `winget settings` and add a config line. My file now looks like below. I exit and re-enter the terminal, and I'm still getting the error, unfortunately. I've tried in both Terminal (PS Core) and in Windows PowerShell.
```
{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },
    
    "experimentalFeatures": {
       "experimentalMSStore": true
    },
    "network": {
       "downloader": "wininet"
    }
}
```

**Comment by vedantmgoyal2009** [comment]
I would suggest doing `shutdown /r` because that fixed the issue **for me**.

**Comment by Jaifroid** [comment]
You mean reboot the computer? I've done it several times since reporting this issue, but the issue persists! Thanks for the suggestion, though.

**Comment by vedantmgoyal2009** [comment]
Can you please send me the output of `msinfo32`? Please export it as text file and send:
![image](https://user-images.githubusercontent.com/83997633/131243297-3dcf95d4-29f5-48d3-8f75-1c165f73201c.png)

**Comment by Jaifroid** [comment]
So, I tried this out in Windows Sandbox using the SandboxTest script. Same error there, both when testing a new manifest and the current version... I guess Windows Sandbox inherits the host's dlls and is not a true clean environment?

![image](https://user-images.githubusercontent.com/4304337/132460565-7c3c7170-1d45-41ac-b7cf-142339660ca3.png)

**Comment by jedieaston** [comment]
> Windows Sandbox inherits the host's dlls and is not a true clean environment

Yeah, it's kind of fuzzy exactly what the Sandbox shares and what it doesn't. The docs are pretty lacking, IMO, but they're here: https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-architecture. I bet that's what's happening.

If you feel like going on a adventure, running a "in-place upgrade" using the [Media Creation Tool](https://www.microsoft.com/en-us/software-download/windows10) (click Download tool now, when its running follow the options for upgrading your current PC) will get you clean copies of those DLLs, and shouldn't mess with anything on your box (presuming you are on 21H1, it'll just get you fresh copies of everything). It should fix your problem, although I didn't suggest it until now because it's kind of a silly way to fix it.

**Comment by OfficialEsco** [comment]
Huh, i just had a client with this issue when executing the appxpackage, bing brought me to this thread 🤔
And somehow after KB5005565 automatically installed and rebooted it works..

**Comment by denelon** [comment]
@OfficialEsco Thanks for mentioning this!

**Comment by denelon** [comment]
@Jaifroid can you give this a try and see if it resolves the issue?

**Comment by Jaifroid** [comment]
@denelon I've just tested again, and the issue has resolved itself since KB5005565 which installed itself yesterday afternoon on my system. I guess some missing or corrupted component was updated. It's a shame we can't identify exactly what was causing the issue, but I'm glad it's resolved. So I'm closing this issue, with thanks to everyone for their help and suggestions.

**Comment by denelon** [comment]
@Jaifroid, thank you for confirming. I'll see about getting this added to the Troubleshooting.md file.
