### ISSUE TITLE
[New Feature]: Upgrade Microsoft.SQLServerManagementStudio

### ISSUE THREAD

**Issue by giggio** [microsoft/winget-pkgs#68467]
### Description of the new feature/enhancement

Current available latest version is `15.0.18420.0`, but `18.12.1` is available online.
See package at: https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/SQLServerManagementStudio
See https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15

**Comment by Trenly** [comment]
@vedantmgoyal2009  / @jedieaston - I think all of SSMS should be changed to have the PackageVersion be the marketing version, and then add the DisplayVersion key to all the AppsAndFeaturesEntries

Thoughts?

**Comment by vedantmgoyal2009** [comment]
I agree.

**Comment by jedieaston** [comment]
Sounds good to me. Is 1.3 being shipped to normal people via the Store yet?

**Comment by Trenly** [comment]
> Sounds good to me. Is 1.3 being shipped to normal people via the Store yet?

I’m not sure. I would think it would go out very very soon, but I don’t know what the plan for it is.

We can always make the changes and wait on merging the PRs until the release

**Comment by mdanish-kh** [comment]
Resolved by #71623

**Comment by giggio** [comment]
Awesome, I think we can close this issue, right?
When is it going to be available?

**Comment by mdanish-kh** [comment]
> Awesome, I think we can close this issue, right? When is it going to be available?

Yes, I think we can close this issue. The package has successfully passed through the publish pipeline and is available when you run `winget install Microsoft.SQLServerManagementStudio`

**Comment by Trenly** [comment]
I still see these versions when running `winget show ssms --versions`
* 15.0.18420.0
* 15.0.18410.0
* 15.0.18390.0
Do these need to have their version corrected to the Marketing Version still?

**Comment by mdanish-kh** [comment]
> I still see these versions when running `winget show ssms --versions`
> 
>     * 15.0.18420.0
> 
>     * 15.0.18410.0
> 
>     * 15.0.18390.0
> 
> 
> Do these need to have their version corrected to the Marketing Version still?

jedieaston has created PRs for them, they are waiting to be merged.
#71660
#71659
#71658

**Comment by Trenly** [comment]
Close with reason: All PRs to fix versions have been merged. Changes will be present once the publish pipeline is un-paused and runs successfully;
